[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["brain_games"]

[project]
name = "hexlet-code"
version = "0.1.0"
dependencies = []

[project.scripts]
brain-games = "brain_games.scripts.brain_games:main"